name: Pre merge cypress tests

on:
  pull_request:
    paths:
      - 'cypress/e2e/**'
      - 'cypress/support/**'

jobs:
  run-tests:
    name: Run Cypress Tests
    permissions:
      contents: read
      pull-requests: write  # Ensure pull-requests write permission
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run test-ui-headless

      - name: Discover and group results
        id: group-results
        run: |
          # Locate the JSON report
          REPORT_FILE="cypress/reports/merged-report.json"
          
          # Initialize counters
          api_total=0
          api_pass=0
          api_fail=0
          ui_total=0
          ui_pass=0
          ui_fail=0

          # Parse JSON and group results
          jq -c '.results[]' "$REPORT_FILE" | while read -r result; do
            file=$(echo "$result" | jq -r '.file')
            total=$(echo "$result" | jq '[.suites[].tests | length] | add')
            passed=$(echo "$result" | jq '[.suites[].tests[] | select(.pass == true)] | length')
            failed=$(echo "$result" | jq '[.suites[].tests[] | select(.fail == true)] | length')

            if [[ "$file" == *"apiTests"* ]]; then
              api_total=$((api_total + total))
              api_pass=$((api_pass + passed))
              api_fail=$((api_fail + failed))
            elif [[ "$file" == *"uiTests"* ]]; then
              ui_total=$((ui_total + total))
              ui_pass=$((ui_pass + passed))
              ui_fail=$((ui_fail + failed))
            fi
          done

          # Create Markdown summary
          echo "| **Test Type** | **Total** | **Passed** | **Failed** |" > test-summary.md
          echo "|--------------|-----------|------------|------------|" >> test-summary.md
          echo "| API Tests    | $api_total | $api_pass  | $api_fail  |" >> test-summary.md
          echo "| UI Tests     | $ui_total  | $ui_pass   | $ui_fail   |" >> test-summary.md

          # Debugging: Print Markdown file
          cat test-summary.md

      - name: Post summary as PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: test-summary.md
          recreate: true
