name: Pre merge cypress tests

on:
  pull_request:
    paths:
      - 'cypress/e2e/**'
      - 'cypress/support/**'

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '1'

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

  tests:
    name: Run Tests and Upload Report
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run Cypress tests
        run: | 
          npm run test-headless

      - name: Upload Cypress test report
        uses: actions/upload-artifact@v3
        with:
          name: cypress-report
          path: cypress/reports/merged-report.html
